/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Diabetes.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Diabetes: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("sy", () => this.@sy, val => this.@sy = val);
			VarDef("passage", () => this.@passage, val => this.@passage = val);
			VarDef("illness", () => this.@illness, val => this.@illness = val);
			VarDef("spassage", () => this.@spassage, val => this.@spassage = val);
			VarDef("ready", () => this.@ready, val => this.@ready = val);
		}

		public StoryVar @sy;
		public StoryVar @passage;
		public StoryVar @illness;
		public StoryVar @spassage;
		public StoryVar @ready;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Diabetes()
	{
		this.StartPassage = "Intro";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Illness

	void passage1_Init()
	{
		this.Passages[@"Illness"] = new StoryPassage(@"Illness", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Okay, what do you want to know?");
		
		Vars.sy  = macros1.a("fatigue", "high_blood_pressure", "weight_loss", "thirst", "hunger", "irritability","frequent_urination","frequent_infections","blurred_vision");
		
		yield return link("Have you had a fever?", "Fever", null);
		
		Vars.passage  = "Illness";
		
		Vars.illness  = "Illness";
		
		yield return link("Let us talk some more about your life", Vars.spassage, null);
		yield break;
	}


	// .............
	// #2: Fever

	void passage2_Init()
	{
		this.Passages[@"Fever"] = new StoryPassage(@"Fever", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		if(Vars.sy .Contains("fever")) {
			
			yield return text("	Yes, I've been feeling hot but also cold at the same time. Sometimes I 		sweat when it is cold.");
			
		}
		else {
			
			yield return text("	I haven't been having a fever.");
			
		}
		
		
		yield return link("Have you been experiencing nausea?", "Nausea", null);
		
		Vars.passage  = "Fever";
		
		yield return link("Let us talk some more about your work and life", Vars.spassage, null);
		yield break;
	}


	// .............
	// #3: Nausea

	void passage3_Init()
	{
		this.Passages[@"Nausea"] = new StoryPassage(@"Nausea", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		if(Vars.sy .Contains("fever")) {
			
			
			if(Vars.sy .Contains("nausea")) {
				
				yield return text("		Yes, I have had such a bad feeling whenever I sit down or stand up.");
				
				
				yield return link("Have you lost your appetite?", "Appetite", null);
				
				
				
			}
			else {
				
				yield return text("		No. Like I said. I'm fit as a fiddle.");
				
				
				yield return link("Do you have any phlegm in your throat or chest?", "Phlegm", null);
				
				
			}
			
		}
		else {
			
			
			if(Vars.sy .Contains("nausea")) {
				
				yield return text("		Yes, I have had such a bad feeling whenever I sit down or stand up.");
				
				
				yield return link("Have you been getting headaches?", "Headaches", null);
				
				
			}
			else {
				
				yield return text("		Only when I get these intense cravings and eat too much.");
				
				
				yield return link("Have you been struggling to breath or been breathing heavily?", "Short of breath", null);
				
				
			}
			
		}
		
		Vars.passage  = "Nausea";
		
		yield return link("Let us talk some more about your work and life", Vars.spassage, null);
		yield break;
	}


	// .............
	// #4: Appetite

	void passage4_Init()
	{
		this.Passages[@"Appetite"] = new StoryPassage(@"Appetite", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		if (Vars.sy.Contains ("fever") && Vars.sy.Contains ("nausea") && Vars.sy.Contains ("loss_of_appetite")) {
			
			yield return text("	Yes, I haven't felt hungry recently but it's saving me money.");
			
			yield return text("	You have hepatitus A");
			
		}
		else {
			
			yield return text("	No, I'm as hungry as I always am.");
			
			yield return text("	You have pneumonia");
			
		}
		
		yield return link("I am ready to make a diagnosis", "Diagnose", null);
		
		Vars.passage  = "Appetite";
		
		yield return link("Let us talk some more about your work and life", Vars.spassage, null);
		
		Vars.ready  = "yes";
		yield break;
	}


	// .............
	// #5: Phlegm

	void passage5_Init()
	{
		this.Passages[@"Phlegm"] = new StoryPassage(@"Phlegm", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		if (Vars.sy.Contains ("fever") && Vars.sy.Contains ("nausea") && Vars.sy.Contains ("phlegm")) {
			
			yield return text("	Yes and it comes up when I cough. It's especially bad when I wake up.");
			
			yield return text("	You have the flu");
			
		}
		else {
			
			yield return text("	No my throat is very clear and I don't feel any phlegm.");
			
			
			
		}
		
		yield return link("I am ready to make a diagnosis", "Diagnose", null);
		
		Vars.passage  = "Phlegm";
		
		yield return link("Let us talk some more about your work and life", Vars.spassage, null);
		
		Vars.ready  = "yes";
		yield break;
	}


	// .............
	// #6: Headaches

	void passage6_Init()
	{
		this.Passages[@"Headaches"] = new StoryPassage(@"Headaches", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		if (Vars.sy.Contains ("nausea") && Vars.sy.Contains ("headaches")) {
			
			yield return text("	Yes very sore headaches!");
			
			yield return text("	you have codein");
			
		}
		else {
			
			yield return text("	No, I haven't been getting any headaches.");
			
			yield return text("	you have stress");
			
		}
		
		yield return link("I am ready to make a diagnosis", "Diagnose", null);
		
		Vars.passage  = "Headaches";
		
		yield return link("Let us talk some more about your work and life", Vars.spassage, null);
		
		Vars.ready  = "yes";
		yield break;
	}


	// .............
	// #7: Short of breath

	void passage7_Init()
	{
		this.Passages[@"Short of breath"] = new StoryPassage(@"Short of breath", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		if(Vars.sy .Contains(macros1.a("short_of_breath"))) {
			
			yield return text("	Yes, I often struggle to catch my breath and start feeling short of breath even when I don't exercise.");
			
			yield return text("	you have hypertension");
			
		}
		else {
			
			yield return text("	No. I do feel it when I go up stairs but that is normal for me.");
			
			yield return text("	you have diabetes");
			
		}
		
		yield return link("I am ready to make a diagnosis", "Diagnose", null);
		
		Vars.passage  = "Short of breath";
		
		yield return link("Let us talk some more about your work and life", Vars.spassage, null);
		
		Vars.ready  = "yes";
		yield break;
	}


	// .............
	// #8: Intro

	void passage8_Init()
	{
		this.Passages[@"Intro"] = new StoryPassage(@"Intro", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Patient: \"I came here on the recommendation of my partner. They say they're worried about my health. They think my immune system is weak from all that pap I eat and all that coke I drink but I'm fit as a fiddle. I'm just here for their peace of mind.\"");
		
		
		yield return text("Dr: Well let's see then.");
		
		Vars.passage  = "Illness";
		
		Vars.spassage  = "Intro";
		
		Vars.ready  = "no";
		
		yield return link("have you lost weight recently?", "Weight loss story", null);
		
		yield return link("have you been feeling unusually tired?", "Fatigue story", null);
		
		yield return link("Have you been feeling hungry?", "Hunger story", null);
		
		yield return link("How have your relationships with friends and family been? ", "Irritability story", null);
		
		yield return link("Notice anything abnormal about your body?.", "Illness", null);
		yield break;
	}


	// .............
	// #9: Family History

	void passage9_Init()
	{
		this.Passages[@"Family History"] = new StoryPassage(@"Family History", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("My family does have a history of diabetes. My brother recently got diagnosed and my father has had it for ages. I guess the signs are there and I'm at risk. My family is worried about me and I'm a bit worried too.");
		
		Vars.spassage  = "Family History";
		
		if(Vars.ready == "no") {
			
			
			yield return link("I'm the doctor here. Let me check you for symptoms", Vars.passage, null);
			
		}
		else {
			
			yield return link("I think that I am ready to make a diagnosis", "Diagnose", null);
			
		}
		
		yield break;
	}


	// .............
	// #10: Weight loss story

	void passage10_Init()
	{
		this.Passages[@"Weight loss story"] = new StoryPassage(@"Weight loss story", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("I don't see how my diet is a problem. I eat as much of anything I want and ifanything, I've lost weight in the past year.");
		
		Vars.spassage  = "Weight loss story";
		
		yield return link("Does your family have a history of illness?", "Family History", null);
		
		yield return link("I'm the doctor here. Let me check you for symptoms", Vars.passage, null);
		yield break;
	}


	// .............
	// #11: Fatigue story

	void passage11_Init()
	{
		this.Passages[@"Fatigue story"] = new StoryPassage(@"Fatigue story", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("I have trouble climbing the stairs at home but I think that's just me getting older.");
		
		Vars.spassage  = "Fatigue story";
		
		yield return link("Does your family have any history of illness?", "Family History", null);
		
		yield return link("I'm the doctor here. Let me check you for symptoms", Vars.passage, null);
		yield break;
	}


	// .............
	// #12: Hunger story

	void passage12_Init()
	{
		this.Passages[@"Hunger story"] = new StoryPassage(@"Hunger story", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("I eat way more than I used to but I see now problem with it. My grandmother always used to say an apppetite of any kind was healthy. I snack throughout the day. Mostly from the vending machine at work.");
		
		Vars.spassage  = "Hunger story";
		
		yield return link("Does your family have a history of illness?", "Family History", null);
		
		yield return link("I'm the doctor here. Let me check you for symptoms", Vars.passage, null);
		yield break;
	}


	// .............
	// #13: Irritability story

	void passage13_Init()
	{
		this.Passages[@"Irritability story"] = new StoryPassage(@"Irritability story", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("My family gets on my nerves and I get annoyed with the noise my collegues make. They call me \"irritable\" but I think it's justified for the hell they put me through.");
		
		Vars.spassage  = "Irritability story";
		
		yield return link("Does your family have a history of illness", "Family History", null);
		
		yield return link("I'm the doctor here. Let me check you for symptoms", Vars.passage, null);
		yield break;
	}


	// .............
	// #14: Diagnose

	void passage14_Init()
	{
		this.Passages[@"Diagnose"] = new StoryPassage(@"Diagnose", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield break;
	}


}