/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Template.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @Template: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
			VarDef("sy", () => this.@sy, val => this.@sy = val);
			VarDef("passage", () => this.@passage, val => this.@passage = val);
			VarDef("illness", () => this.@illness, val => this.@illness = val);
			VarDef("spassage", () => this.@spassage, val => this.@spassage = val);
			VarDef("ready", () => this.@ready, val => this.@ready = val);
		}

		public StoryVar @sy;
		public StoryVar @passage;
		public StoryVar @illness;
		public StoryVar @spassage;
		public StoryVar @ready;
	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@Template()
	{
		this.StartPassage = "Intro";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: TB

	void passage1_Init()
	{
		this.Passages[@"TB"] = new StoryPassage(@"TB", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Okay, what do you want to know?");
		yield return lineBreak();
		Vars.sy  = macros1.a("weight_loss", "loss_of_appetite", "night_sweats", "fever", "coughing", "chills","chest_pain");
		yield return lineBreak();
		yield return link("Have you had a fever?", "Fever", null);
		yield return lineBreak();
		Vars.passage  = "TB";
		yield return lineBreak();
		Vars.illness  = "TB";
		yield return lineBreak();
		yield return link("Let us talk some more about your work and life", Vars.spassage, null);
		yield break;
	}


	// .............
	// #2: Fever

	void passage2_Init()
	{
		this.Passages[@"Fever"] = new StoryPassage(@"Fever", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		if(Vars.sy .Contains("fever")) {
			yield return lineBreak();
			yield return text("	Yes, I've been feeling hot but also cold at the same time. Sometimes I 		sweat when it is cold.");
			yield return lineBreak();
		}
		else {
			yield return lineBreak();
			yield return text("	I haven't been having a fever.");
			yield return lineBreak();
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return link("Have you been experiencing nausea?", "Nausea", null);
		yield return lineBreak();
		Vars.passage  = "Fever";
		yield return lineBreak();
		yield return link("Let us talk some more about your work and life", Vars.spassage, null);
		yield break;
	}


	// .............
	// #3: Nausea

	void passage3_Init()
	{
		this.Passages[@"Nausea"] = new StoryPassage(@"Nausea", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		if(Vars.sy .Contains("fever")) {
			yield return lineBreak();
			yield return text("	");
			if(Vars.sy .Contains("nausea")) {
				yield return lineBreak();
				yield return text("		Yes, I have had such a bad feeling whenever I sit down or stand up.");
				yield return lineBreak();
				yield return text("		");
				yield return link("Have you lost your appetite?", "Appetite", null);
				yield return text("	");
				yield return lineBreak();
				yield return text("	");
			}
			else {
				yield return lineBreak();
				yield return text("		No, not at all.");
				yield return lineBreak();
				yield return text("		");
				yield return link("Do you have any phlegm in your throat or chest?", "Phlegm", null);
				yield return lineBreak();
				yield return text("	");
			}
			yield return lineBreak();
		}
		else {
			yield return lineBreak();
			yield return text("	");
			if(Vars.sy .Contains("nausea")) {
				yield return lineBreak();
				yield return text("		Yes, I have had such a bad feeling whenever I sit down or stand up.");
				yield return lineBreak();
				yield return text("		");
				yield return link("Have you been getting headaches?", "Headaches", null);
				yield return lineBreak();
				yield return text("	");
			}
			else {
				yield return lineBreak();
				yield return text("		No, not at all.");
				yield return lineBreak();
				yield return text("		");
				yield return link("Have you been struggling to breath or been breathing heavily?", "Short of breath", null);
				yield return lineBreak();
				yield return text("	");
			}
			yield return lineBreak();
		}
		yield return lineBreak();
		Vars.passage  = "Nausea";
		yield return lineBreak();
		yield return link("Let us talk some more about your work and life", Vars.spassage, null);
		yield break;
	}


	// .............
	// #4: Appetite

	void passage4_Init()
	{
		this.Passages[@"Appetite"] = new StoryPassage(@"Appetite", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		if(Vars.sy .Contains(v("all").AsMemberOf[macros1.a("fever","nausea","loss_of_appetite")])) {
			yield return lineBreak();
			yield return text("	Yes, I haven't felt hungry recently but it's saving me money.");
			yield return lineBreak();
			yield return text("	You have hepatitus A");
			yield return lineBreak();
		}
		else {
			yield return lineBreak();
			yield return text("	No, I'm as hungry as I always am.");
			yield return lineBreak();
			yield return text("	You have pneumonia");
			yield return lineBreak();
		}
		yield return lineBreak();
		yield return link("I am ready to make a diagnosis", "Diagnose", null);
		yield return lineBreak();
		Vars.passage  = "Appetite";
		yield return lineBreak();
		yield return link("Let us talk some more about your work and life", Vars.spassage, null);
		yield return lineBreak();
		Vars.ready  = "yes";
		yield break;
	}


	// .............
	// #5: Phlegm

	void passage5_Init()
	{
		this.Passages[@"Phlegm"] = new StoryPassage(@"Phlegm", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		if(Vars.sy .Contains(v("all").AsMemberOf[macros1.a("fever","nausea","phlegm")])) {
			yield return lineBreak();
			yield return text("	Yes and it comes up when I cough. It's especially bad when I wake up.");
			yield return lineBreak();
			yield return text("	You have the flu");
			yield return lineBreak();
		}
		else {
			yield return lineBreak();
			yield return text("	No my throat is very clear and I don't feel any phlegm.");
			yield return lineBreak();
			yield return text("	You have the TB");
			yield return lineBreak();
		}
		yield return lineBreak();
		yield return link("I am ready to make a diagnosis", "Diagnose", null);
		yield return lineBreak();
		Vars.passage  = "Phlegm";
		yield return lineBreak();
		yield return link("Let us talk some more about your work and life", Vars.spassage, null);
		yield return lineBreak();
		Vars.ready  = "yes";
		yield break;
	}


	// .............
	// #6: Headaches

	void passage6_Init()
	{
		this.Passages[@"Headaches"] = new StoryPassage(@"Headaches", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		if(Vars.sy .Contains(v("all").AsMemberOf[macros1.a("nausea","headaches")])) {
			yield return lineBreak();
			yield return text("	Yes very sore headaches!");
			yield return lineBreak();
			yield return text("	you have codein");
			yield return lineBreak();
		}
		else {
			yield return lineBreak();
			yield return text("	No, I haven't been getting any headaches.");
			yield return lineBreak();
			yield return text("	you have stress");
			yield return lineBreak();
		}
		yield return lineBreak();
		yield return link("I am ready to make a diagnosis", "Diagnose", null);
		yield return lineBreak();
		Vars.passage  = "Headaches";
		yield return lineBreak();
		yield return link("Let us talk some more about your work and life", Vars.spassage, null);
		yield return lineBreak();
		Vars.ready  = "yes";
		yield break;
	}


	// .............
	// #7: Short of breath

	void passage7_Init()
	{
		this.Passages[@"Short of breath"] = new StoryPassage(@"Short of breath", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		if(Vars.sy .Contains(macros1.a("short_of_breath"))) {
			yield return lineBreak();
			yield return text("	Yes, I often struggle to catch my breath and start feeling short of breath even when I don't exercise.");
			yield return lineBreak();
			yield return text("	you have hypertension");
			yield return lineBreak();
		}
		else {
			yield return lineBreak();
			yield return text("	No. I do feel it when I go up stairs but that is normal for me.");
			yield return lineBreak();
			yield return text("	you have diabetes");
			yield return lineBreak();
		}
		yield return lineBreak();
		yield return link("I am ready to make a diagnosis", "Diagnose", null);
		yield return lineBreak();
		Vars.passage  = "Short of breath";
		yield return lineBreak();
		yield return link("Let us talk some more about your work and life", Vars.spassage, null);
		yield return lineBreak();
		Vars.ready  = "yes";
		yield break;
	}


	// .............
	// #8: Intro

	void passage8_Init()
	{
		this.Passages[@"Intro"] = new StoryPassage(@"Intro", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Patient: This is actually my second time back this week. I just don’t seem to be getting any better. I saw another doctor and he said I have TB but he has no idea what he’s talking about. I’m not coughing blood at all.");
		yield return lineBreak();
		yield return text("Dr: Well let's take a look and see what we can see. Tell me,");
		yield return lineBreak();
		Vars.passage  = "TB";
		yield return lineBreak();
		Vars.spassage  = "Intro";
		yield return lineBreak();
		Vars.ready  = "no";
		yield return lineBreak();
		yield return link("have you lost weight recently?", "Weight loss story", null);
		yield return lineBreak();
		yield return link("have you been feeling unusually tired at all?", "Fatigue story", null);
		yield return lineBreak();
		yield return link("Have you been coughing or had any chest pains?", "Coughing story", null);
		yield return lineBreak();
		yield return link("How has your sleep been?", "Night sweats story", null);
		yield return lineBreak();
		yield return link("I'm the doctor here. Tell me about your symptoms", "TB", null);
		yield break;
	}


	// .............
	// #9: Work

	void passage9_Init()
	{
		this.Passages[@"Work"] = new StoryPassage(@"Work", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("I'm a security guard at the mall. I start my shift at 6PM and end at 4AM the next day, then I walk to catch the taxi back home and arrive home at 5:30AM. I'm always so tired and don't see my children because they leave before I get home. The cold weather must be causing me to catch a cold, but I can't have a cold because they won't want me to work and I can't miss work. Please find me some medicine for the cold and I'll be on my way so that I can sleep before tonight.");
		yield return lineBreak();
		Vars.spassage  = "Work";
		yield return lineBreak();
		if(Vars.ready == "no") {
			yield return lineBreak();
			yield return text("	");
			yield return link("I'm the doctor here. Let me check you for symptoms", Vars.passage, null);
			yield return lineBreak();
		}
		else {
			yield return lineBreak();
			yield return link("I think that I am ready to make a diagnosis", "Diagnose", null);
			yield return lineBreak();
		}
		yield return lineBreak();
		yield break;
	}


	// .............
	// #10: Weight loss story

	void passage10_Init()
	{
		this.Passages[@"Weight loss story"] = new StoryPassage(@"Weight loss story", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("Yeah I have, but I always do when I'm stressed and I've been working really hard recently. It's just stress.");
		yield return lineBreak();
		Vars.spassage  = "Weight loss story";
		yield return lineBreak();
		yield return link("What's your profession?", "Work", null);
		yield return lineBreak();
		yield return link("I'm the doctor here. Let me check you for symptoms", Vars.passage, null);
		yield break;
	}


	// .............
	// #11: Fatigue story

	void passage11_Init()
	{
		this.Passages[@"Fatigue story"] = new StoryPassage(@"Fatigue story", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("I've been working the night shift and it's winter so of course I'll be feeling tired.");
		yield return lineBreak();
		Vars.spassage  = "Fatigue story";
		yield return lineBreak();
		yield return link("Tell me about your work, what do you do?", "Work", null);
		yield return lineBreak();
		yield return link("I'm the doctor here. Let me check you for symptoms", Vars.passage, null);
		yield break;
	}


	// .............
	// #12: Coughing story

	void passage12_Init()
	{
		this.Passages[@"Coughing story"] = new StoryPassage(@"Coughing story", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("At home the only way to keep warm is with the fire, so we light it in the evenings but the smoke always gets everywhere because we also block the holes for the wind. At work I'm also coughing now because the cold air hurts my chest.");
		yield return lineBreak();
		Vars.spassage  = "Coughing story";
		yield return lineBreak();
		yield return link("Tell me about your work, what do you do?", "Work", null);
		yield return lineBreak();
		yield return link("I'm the doctor here. Let me check you for symptoms", Vars.passage, null);
		yield break;
	}


	// .............
	// #13: Night sweats story

	void passage13_Init()
	{
		this.Passages[@"Night sweats story"] = new StoryPassage(@"Night sweats story", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("I can't sleep recently. Last month I had to shoot a man at work and I haven't slept well since. I work the night shift so I only sleep in the morning and I always wake up hot and sweating.");
		yield return lineBreak();
		Vars.spassage  = "Night sweats story";
		yield return lineBreak();
		yield return link("What work do you do?", "Work", null);
		yield return lineBreak();
		yield return link("I'm the doctor here. Let me check you for symptoms", Vars.passage, null);
		yield break;
	}


	// .............
	// #14: Diagnose

	void passage14_Init()
	{
		this.Passages[@"Diagnose"] = new StoryPassage(@"Diagnose", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield break;
	}


}