/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: HIVArc.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @HIVArc: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@HIVArc()
	{
		this.StartPassage = "HIVArc";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: HIVArc

	void passage1_Init()
	{
		this.Passages[@"HIVArc"] = new StoryPassage(@"HIVArc", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Good morning doctor, I have HIV. Please can you give me antiretrovirals.");
		yield return lineBreak();
		yield return link("How do you know that you have HIV?", "Q1", null);
		yield return lineBreak();
		yield return link("Check symptoms", "Q2", null);
		yield break;
	}


	// .............
	// #2: Q1

	void passage2_Init()
	{
		this.Passages[@"Q1"] = new StoryPassage(@"Q1", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("I slept with another man last night and when we looked, the condom was broken.");
		yield return lineBreak();
		yield return link("Does this man have HIV?", "Q3", null);
		yield return lineBreak();
		yield return link("Why did you sleep with another man? Are you homosexual?", "Why did you sleep with another man? Are you homosexual?", null);
		yield return lineBreak();
		yield return link("Check Symptoms", "Q2", null);
		yield break;
	}


	// .............
	// #3: Q3

	void passage3_Init()
	{
		this.Passages[@"Q3"] = new StoryPassage(@"Q3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Yes he does have HIV because he has slept with another man before me.");
		yield return lineBreak();
		yield return link("Has he been tested for HIV?", "Has he been tested for HIV?", null);
		yield return lineBreak();
		yield return link("Check Symptoms", "Q2", null);
		yield break;
	}


	// .............
	// #4: Has he been tested for HIV?

	void passage4_Init()
	{
		this.Passages[@"Has he been tested for HIV?"] = new StoryPassage(@"Has he been tested for HIV?", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("No, but he is gay like me and has had sex with another man. Even if he didn't have HIV before, he has HIV now after we had sex.");
		yield return lineBreak();
		yield return link("Wait, neither you nor he has been tested for HIV?", "Wait, neither you nor he has been tested for HIV?", null);
		yield return lineBreak();
		yield return link("Check Symptoms", "Q2", null);
		yield break;
	}


	// .............
	// #5: Wait, neither you nor he has been tested for HIV?

	void passage5_Init()
	{
		this.Passages[@"Wait, neither you nor he has been tested for HIV?"] = new StoryPassage(@"Wait, neither you nor he has been tested for HIV?", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("No but we don't need to test because we are gay, we have given each other HIV because we had sex and the condom broke!");
		yield return lineBreak();
		yield return link("HIV isn't contracted through homosexual sex only, and it can only be passed on by someone who has HIV. You may be lucky and not have HIV.", "HIV isn't contracted through homosexual sex only, and it can only be passed on by someone who has HIV. You may be lucky and not have HIV.", null);
		yield return lineBreak();
		yield return link("Check Symptoms", "Q2", null);
		yield break;
	}


	// .............
	// #6: HIV isn't contracted through homosexual sex only, and it can only be passed on by someone who has HIV. You may be lucky and not have HIV.

	void passage6_Init()
	{
		this.Passages[@"HIV isn't contracted through homosexual sex only, and it can only be passed on by someone who has HIV. You may be lucky and not have HIV."] = new StoryPassage(@"HIV isn't contracted through homosexual sex only, and it can only be passed on by someone who has HIV. You may be lucky and not have HIV.", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("You don't know what you are talking about. Where does HIV come from? It comes from our sins, like having sex with other men. Please, just give me the ARVs so that I can leave.");
		yield return lineBreak();
		yield return link("Prescribe ARVs", "Prescribe ARVs", null);
		yield return lineBreak();
		yield return link("Recommend an HIV test", "Recommend an HIV test", null);
		yield return lineBreak();
		yield return link("Check Symptoms", "Q2", null);
		yield break;
	}


	// .............
	// #7: Prescribe ARVs

	void passage7_Init()
	{
		this.Passages[@"Prescribe ARVs"] = new StoryPassage(@"Prescribe ARVs", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Thank you. I won't have long now, but maybe I won't suffer.");
		yield return lineBreak();
		yield return link("You can live with HIV, many people have lived full lives with HIV, just be sure to take your ARVs correctly", "You can live with HIV, many people have lived full lives with HIV, just be sure to take your ARVs correctly", null);
		yield return lineBreak();
		yield return link("Goodbye", "Goodbye", null);
		yield break;
	}


	// .............
	// #8: Recommend an HIV test

	void passage8_Init()
	{
		this.Passages[@"Recommend an HIV test"] = new StoryPassage(@"Recommend an HIV test", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Why must you waste my time like this? I am dying already, I can feel myself dying. I waited in this queue for four hours and now I must go wait in another queue? I do not have time. You think that you know everything, but I know that I am dying.");
		yield return lineBreak();
		yield return link("Goodbye", "Goodbye", null);
		yield return lineBreak();
		yield return link("You can't know that for certain", "You can't know that for certain", null);
		yield break;
	}


	// .............
	// #9: You can live with HIV, many people have lived full lives with HIV, just be sure to take your ARVs correctly

	void passage9_Init()
	{
		this.Passages[@"You can live with HIV, many people have lived full lives with HIV, just be sure to take your ARVs correctly"] = new StoryPassage(@"You can live with HIV, many people have lived full lives with HIV, just be sure to take your ARVs correctly", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #10: Goodbye

	void passage10_Init()
	{
		this.Passages[@"Goodbye"] = new StoryPassage(@"Goodbye", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		using (Group("em", true)) {
			yield return text("The patient leaves");
		}
		yield break;
	}


	// .............
	// #11: You can't know that for certain

	void passage11_Init()
	{
		this.Passages[@"You can't know that for certain"] = new StoryPassage(@"You can't know that for certain", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return link("Next patient", "Next patient", null);
		yield break;
	}


	// .............
	// #12: Next patient

	void passage12_Init()
	{
		this.Passages[@"Next patient"] = new StoryPassage(@"Next patient", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #13: Why did you sleep with another man? Are you homosexual?

	void passage13_Init()
	{
		this.Passages[@"Why did you sleep with another man? Are you homosexual?"] = new StoryPassage(@"Why did you sleep with another man? Are you homosexual?", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("I have sinful thoughts, and believe that I love this man. They told me that it was only lust and not love, but I love this man. Now I will die for my sins, but I cannot live with these demons.");
		yield return lineBreak();
		yield return link("Why will you die?", "Why will you die?", null);
		yield return lineBreak();
		yield return link("Loving another man is not sinful", "Loving another man is not sinful", null);
		yield return lineBreak();
		yield return link("You deserve to get HIV for having sex with another man", "You deserve to get HIV for having sex with another man", null);
		yield return lineBreak();
		yield return link("Check Symptoms", "Q2", null);
		yield break;
	}


	// .............
	// #14: Why will you die?

	void passage14_Init()
	{
		this.Passages[@"Why will you die?"] = new StoryPassage(@"Why will you die?", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("Because having sinful sex causes HIV.");
		yield return lineBreak();
		yield return link("Q3", "Q3", null);
		yield return lineBreak();
		yield return link("Check Symptoms", "Q2", null);
		yield break;
	}


	// .............
	// #15: Loving another man is not sinful

	void passage15_Init()
	{
		this.Passages[@"Loving another man is not sinful"] = new StoryPassage(@"Loving another man is not sinful", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("I have read the bible and listened to my pastor. I know that I have commited sin, you are a doctor not a priest. Please, give me medication so that I can leave.");
		yield return lineBreak();
		yield return link("HIV isn't contracted through homosexual sex only, and it can only be passed on by someone who has HIV. You may be lucky and not have HIV.", "HIV isn't contracted through homosexual sex only, and it can only be passed on by someone who has HIV. You may be lucky and not have HIV.", null);
		yield return lineBreak();
		yield return link("Check Symptoms", "Q2", null);
		yield break;
	}


	// .............
	// #16: You deserve to get HIV for having sex with another man

	void passage16_Init()
	{
		this.Passages[@"You deserve to get HIV for having sex with another man"] = new StoryPassage(@"You deserve to get HIV for having sex with another man", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("I will die because of you. You must remember that you have killed someone when you try to sleep at night, in your nice big house.");
		yield return lineBreak();
		yield return link("Goodbye", "Goodbye", null);
		yield break;
	}


	// .............
	// #17: Q2

	void passage17_Init()
	{
		this.Passages[@"Q2"] = new StoryPassage(@"Q2", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


	// .............
	// #18: Does this man have HIV?

	void passage18_Init()
	{
		this.Passages[@"Does this man have HIV?"] = new StoryPassage(@"Does this man have HIV?", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text("Double-click this passage to edit it.");
		yield break;
	}


}